### PR TITLE
DR-1893: Retry Firestore transactions

### PR DESCRIPTION
**Pull request by snf2ye**
Small change to unblock alpha. I've created follow on tickets to do more clean up and further investigate our firestore transactions.

### CODE REVIEW

**Review by nmalfroy — APPROVED** [review]
Ok, I think this makes sense.  Nice!

**Review by samanehsan — APPROVED** [review]
Lgtm! thanks!

**Review by fboulnois — APPROVED** [review]
lgtm, makes sense!

**Comment by snf2ye** [comment]
One connected test failing - Azure test, so not related to these changes.

**Pull request merged**
