### PR TITLE
DR-830 Separating connected tests from integration

### PR DESCRIPTION
**Pull request by smark88**

### CODE REVIEW

**Review by fboulnois — CHANGES_REQUESTED** [review]
I am concerned about the amount of duplication across our workflows. I wonder if there's a better way to address it. Let's discuss.

**Comment by smark88** [comment]
> I am concerned about the amount of duplication across our workflows. I wonder if there's a better way to address it. Let's discuss.

As stated we can fix the duplicates later but they all will remain in some way. The vanilla runner will have to install and configure itself every time. In this case test-connected and integration are separate runners.

**Comment by smark88** [comment]
I think this is good from a deployment perspective and will be opening it for PR but I have concerns about the integration test failing so much. @thathert @fboulnois

**Comment by thathert** [comment]
I'm tempted to say let's put this on hold for a while until we figure out the integration env failures?

**Comment by smark88** [comment]
Closed till further notice

**Pull request closed without merging**
