### PR TITLE
DR-54 Configure SLF4J and Logback for logging

### PR DESCRIPTION
**Pull request by ddietterich**
This PR gets us configured for logging. I'm sure we will make changes going forward; this is a first cut to support development.

I updated build.gradle to include SLF4J logging shim. By coding against that, we can change out what logger is being used underneath. I added some logging to the stairway unit tests, so there are some examples in our code.

The convention I have seen is to use the full class name (e.g., bio.terra.<package>.<class> for the logger name. That gives maximum granularity for controlling what gets logged. That seems a bit precious for the tests, so I didn't include the <class> part.

I chose logback for the logger. It is popular and reported to be very performant. It also has great support for live log configuration changes. I made a logback configuration file that writes to `logs/datarepo.log` in your project. It has some comments in it to help guide additions.

I chose to use Groovy to implement the configuration file because it is readable and makes it easy for us to program where we want our logs to go.

BTW - somehow the generated JobModel got merged into github; which shouldn't happen because we have a .gitignore for the generated code. Anyway, this PR deletes that, if it doesn't get removed sooner than this goes in.

### CODE REVIEW

**Review by thathert — COMMENTED** [review]
Thanks for adding this Dan. One thing that I want to check before moving forward with this is  that we're making it easy to aggregate logs. I'd like to use FluentD because I've heard it is a big improvement over Logstash. I know FluentD comes with it's own Java logger but I'd also assume it comes with an agent that can monitor logs and forward them to a source like BigQuery. What are your thoughts on this?

I'm running to the vet now but will have a better chance to investigate when I get back later.

**Review by chrisfarnham — APPROVED** [review]
Per 12 Factor app recommendations (https://12factor.net/logs) I would prefer that all logging go to standard out. The system configuration via fluentd or equiv can route and manage logging.

This is a step forward, let's merge this and improve as described above in an additional PR/task.

**Review by ahaessly — APPROVED** [review]
👍

**Comment by ddietterich** [comment]
@thathert - The reason to use SLF4J is so that when you compose systems, you don't have dueling loggers. Spring integrates with it, so we get the Spring logging and our logging in the same place. Don't know why fluentd decided that they had to be the top interface; seems like a mistake.

@chrisfarnham - The current config I made sends log data to a file and to stdout. My guess is that for local debugging, we will want a local log file. As you suggestion, for production we will only want the stdout stream. With this implementation, we do that by using different logger config files for the different environments.

**Comment by thathert** [comment]
I updated https://broadinstitute.atlassian.net/browse/DR-108 to reflect this discussion. I think it makes sense to log to a file + stdout locally, and just to stdout in the other environments. 

To clarify, I *don't* think we should use the FluentD logger, but instead use it as a log router outside of the app. I like that SLF4J will integrate with Spring logging, and the interface is similar to what I'm used to.

**Pull request merged**
