### PR TITLE
DR-1418 Flow to export snapshot to a workspace

### PR DESCRIPTION
**Pull request by myessail**
snapshotexport

### CODE REVIEW

**Comment by samanehsan** [comment]
I think this looks good! Have you looked into why the integration tests are failing?

**Review by snf2ye — APPROVED** [review]
LGTM (assuming tests pass or identified as one of the known issues)

**Comment by myessail** [comment]
Tests are failing because of https://broadworkbench.atlassian.net/browse/DR-1770, should be able to merge anyways

**Review by samanehsan — APPROVED** [review]
LGTM :octocat:

**Pull request merged**
