### PR TITLE
DR-1508 Follow up: Disable spend profile

### PR DESCRIPTION
**Pull request by snf2ye**

### CODE REVIEW

**Review by fboulnois — COMMENTED** [review]
Nit suggestion: have `/*` and `*/` on the lines before and after the multiline code to comment so that it doesn't modify the indentation and makes for a cleaner diff.

**Review by nmalfroy — APPROVED** [review]
lgtm

**Review by ddietterich — APPROVED** [review]
lgtm

**Review by fboulnois — APPROVED** [review]
nice, diff looks super clean. lgtm!

**Pull request merged**
