### PR TITLE
DR-2018 follow-on: missing @ sign breaking action run

### PR DESCRIPTION
**Pull request by snf2ye**

### CODE REVIEW

**Review by nmalfroy — APPROVED** [review]

**Comment by nmalfroy** [comment]
I'm surprised this didn't fail during the PR runs

**Review by samanehsan — APPROVED** [review]
Good catch! Lgtm :octocat:

**Comment by snf2ye** [comment]
> I'm surprised this didn't fail during the PR runs

 The test run failed w/ the original PR, but I think github actions is in a degraded state and didn't correctly signal on the main PR page that it didn't pass.

**Comment by pshapiro4broad** [comment]
It looks like there's a linter for github workflows that would've caught this typo -- I tested it out with the incorrect code. https://github.com/rhysd/actionlint

**Pull request merged**
