### PR TITLE
PF-934 Bump Stairway to 0.0.62 to pick up the serdes change

### PR DESCRIPTION
**Pull request by ddietterich**
This PR picks up the latest Stairway version that moves serialization/deserialization to the get/put. This is serdes [Phase 2 as described in this document](https://docs.google.com/document/d/1b1VckTBb_V1pCMhoN2GgHnGDR2f8MV2HuwIgDqFc_9M/edit#heading=h.49331srrvaui)

I will leave it to the Jade Core team to decide when the time is right to merge this.

### CODE REVIEW

**Review by pshapiro4broad — APPROVED** [review]

**Review by pshapiro4broad — APPROVED** [review]
Nice! Thanks for updating the calls to `FlightMap.get()` and getting rid of those ugly `force = true` dependencies.

**Review by samanehsan — APPROVED** [review]

**Comment by pshapiro4broad** [comment]
Was there a reason why you updated the `Map.class` cases but not the `List.class` ones?

**Review by fboulnois — APPROVED** [review]
lgtm, 👍 on the dependency cleanup

**Comment by ddietterich** [comment]
> Was there a reason why you updated the `Map.class` cases but not the `List.class` ones?

I updated the ones that broke. I was trying to tiptoe around and make the minimal change.

**Pull request merged**
