### PR TITLE
DR-2042 Update skaffold template and readme to work with newer skaffold version

### PR DESCRIPTION
**Pull request by nmalfroy**

### CODE REVIEW

**Review by fboulnois — COMMENTED** [review]
Is it possible to add Skaffold to the brewfile? https://github.com/DataBiosphere/jade-data-repo/blob/develop/docs/Brewfile

**Comment by nmalfroy** [comment]
> Is it possible to add Skaffold to the brewfile? https://github.com/DataBiosphere/jade-data-repo/blob/develop/docs/Brewfile

Totally.  I wasn't even aware of it.  Just added

**Comment by fboulnois** [comment]
> > Is it possible to add Skaffold to the brewfile? https://github.com/DataBiosphere/jade-data-repo/blob/develop/docs/Brewfile
> 
> Totally. I wasn't even aware of it. Just added

That will make installation really easy!

**Review by fboulnois — APPROVED** [review]

**Review by pshapiro4broad — APPROVED** [review]
Thanks for figuring this out! I'm curious how you ended up debugging it. When I looked at it I couldn't figure out how to get a useful error message from `helm`.

**Review by tlangs — APPROVED** [review]

**Comment by nmalfroy** [comment]
> Thanks for figuring this out! I'm curious how you ended up debugging it. When I looked at it I couldn't figure out how to get a useful error message from `helm`.

Haha, I googled and swore a lot :). I happened to find a github discussion around the behavior change with remote charts

**Pull request merged**
