### PR TITLE
DR-1992 Make IntelliJ pick up the right generated sources dir

### PR DESCRIPTION
**Pull request by tlangs**
Editing the build.gradle to make IntelliJ look in the right place.

### CODE REVIEW

**Review by pshapiro4broad — APPROVED** [review]
Approved!

**Review by snf2ye — APPROVED** [review]

**Review by nmalfroy — COMMENTED** [review]
Awesome! Do you mind creating a Jira for this one?

**Comment by tlangs** [comment]
Done! Sorry, I created this in a fit of rage after IntelliJ put the fully-qualified import in for the billionth time and I forgot to make a ticket 😅

**Comment by nmalfroy** [comment]
Haha, high five for fixing it!

**Pull request merged**
