### PR TITLE
added slack alert fields

### PR DESCRIPTION
**Pull request by smark88**

### CODE REVIEW

**Review by pshapiro4broad — COMMENTED** [review]
LGTM. I thought there was a DR ticket for this work but I couldn't find it.

**Review by pshapiro4broad — APPROVED** [review]

**Review by nmalfroy — APPROVED** [review]

**Review by fboulnois — APPROVED** [review]
This will at least restore the previous status quo. Perhaps once this goes in we can remove the fields that aren't useful.

**Comment by fboulnois** [comment]
> LGTM. I thought there was a DR ticket for this work but I couldn't find it.

Yes, I thought the same thing.

**Comment by smark88** [comment]
> > LGTM. I thought there was a DR ticket for this work but I couldn't find it.
> 
> Yes, I thought the same thing.

+1

**Pull request merged**
