### PR TITLE
Upgrade to openapi 3

### PR DESCRIPTION
**Pull request by myessail**

### CODE REVIEW

**Review by RoriCremer — APPROVED** [review]

**Comment by RoriCremer** [comment]
as long as the tests all pass---is there anything else we need to do to test this? Do we need to regenerate anything?

**Comment by ddietterich** [comment]
There are two places where code is generated for this. One in the main build.gradle and one in the client sub-project.
I am guessing those will have to change.

Opportunistically, if we can move the generated code out from under src and/ into build/, that would be an improvement.

**Comment by nmalfroy** [comment]
Might make sense to compare the swagger json that gets returned currently
with the one that gets returned after this change

**Comment by nmalfroy** [comment]
Yeah, though I think it makes it harder to work with.  I don’t generally
mind having the generated code live in the /generated sub folder

**Comment by ddietterich** [comment]
I have not minded - I put it there in the first place. When I went to convert to the new openapi3 code generators, the plug-in I ended up user was highly opinionated about not putting under src...

**Review by fboulnois — COMMENTED** [review]
Looks like tests are failing due to build failures in the `:generateApi` step

**Pull request closed without merging**
