### PR TITLE
Setup the basic structure of the project:

### PR DESCRIPTION
**Pull request by ddietterich**
- usual gitignore for starters
 - default gradle build, until we have something to build
 - used gradle wrapper so we are independent of any specific gradle people have installed.
 - trivial README.md so the directory structure gets pulled in.

### CODE REVIEW

**Review by ahaessly — COMMENTED** [review]
i couldn't run gradlew. 
got this error: Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

i tried setting GRADLE_USER_HOME but that didn't help

**Comment by ahaessly** [comment]
does the gradlew need to be checked in or can we tell the user to run `gradle wrapper`? the gradle-wrapper.properties had the wrong gradle version for what i had installed.

**Comment by ddietterich** [comment]
It needs to be committed to the repository. I probably missed it on the commit.

**Comment by thathert** [comment]
I needed to bump the gradle version as well, but had no issues otherwise. I think this is ready to go once that commit is pushed.

**Comment by ddietterich** [comment]
I did not miss the gradle wrapper. It is part of the commit.
Two pieces of setup are needed to use the wrapper:

1. When you configure the project in IntelliJ, you have to specify using the wrapper. I'm not sure that setting gets carried along from what is stored in github.
1. To run gradle, you run ./gradlew in the top-level directory of the project. If you use "gradle" from the command line, it will search your path and find the gradle you have installed.

**Pull request merged**
