### PR TITLE
Update GitHub actions to 0.24.0

### PR DESCRIPTION
**Pull request by fboulnois**
Update to 0.24.0 before upgrading to 0.25.0 to ensure action still works.

### CODE REVIEW

**Review by snf2ye — APPROVED** [review]

**Review by snf2ye — APPROVED** [review]
latest LGTM

**Review by ddietterich — APPROVED** [review]
lgtm

**Review by nmalfroy — APPROVED** [review]
Assuming the insides of the 0.24.0 actions image are good this seems reasonable to me.  I'm surprised we didn't need the app credentials and sa_cert before this

**Comment by fboulnois** [comment]
> Assuming the insides of the 0.24.0 actions image are good this seems reasonable to me. I'm surprised we didn't need the app credentials and sa_cert before this

These were added in a recent version, before the credentials were hardcoded.

**Pull request merged**
