### PR TITLE
DR-2281 Remove the DataRepoException class and replace with ErrorReportException

### PR DESCRIPTION
**Pull request by nmalfroy**
which is the base terra common lib class

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]

**Comment by tlangs** [comment]
Why not make `DataRepoException` extend `ErrorReportingException`?

**Comment by nmalfroy** [comment]
Hmm...I suppose I could.  I wasn't really sure what that would get us

**Review by snf2ye — APPROVED** [review]

**Comment by nmalfroy** [comment]
> Why not make `DataRepoException` extend `ErrorReportingException`?

Hmm....you might be onto something...I think there's some encoding that happens based on this class.  I'll try changing it

**Comment by nmalfroy** [comment]
> > Why not make `DataRepoException` extend `ErrorReportingException`?
> 
> Hmm....you might be onto something...I think there's some encoding that happens based on this class. I'll try changing it

Oh wait I can't because then I can't make the common exceptions extend DataRepoException

**Pull request merged**
