### PR TITLE
DR-1398: Increase wait time for new version of perf to spin up

### PR DESCRIPTION
**Pull request by snf2ye**
Additional change: add silent parameter on curl calls to remove extraneous logging.

### CODE REVIEW

**Review by nmalfroy — APPROVED** [review]
Lgtm

**Review by fboulnois — COMMENTED** [review]
Is this still required? I saw your earlier comment on debugging this issue.

**Comment by snf2ye** [comment]
After looking at the logs, it does not appear that a longer wait time would have fixed this issue.

**Comment by snf2ye** [comment]
After further investigating the logs (detailed in Jira ticket: https://broadworkbench.atlassian.net/browse/DR-1398), I think this would be a useful change.

**Review by nmalfroy — APPROVED** [review]

**Review by fboulnois — APPROVED** [review]
lgtm

**Pull request merged**
