### PR TITLE
grafana users

### PR DESCRIPTION
**Pull request by RoriCremer**

### CODE REVIEW

**Review by thathert — APPROVED** [review]
LGTM

**Comment by smark88** [comment]
How does this get mounted in the container?

Seems like you need to add something like this to the config `jade-data-repo/ops/k8s/configs/grafana-config.yaml.ctmpl`

```
  users-dashboard: |-
{{ file "ops/k8s/configs/grafana/users-dashboard.json " | indent 4 }}
```

and something like this in `jade-data-repo/ops/k8s/deployments/grafana.yaml`

```
        - mountPath: /var/lib/grafana/dashboards/bigquery-logs
          name: "grafana-config-bigquery-logs"
```
```
      - name: "grafana-config-bigquery-logs"
        configMap:
          name: "grafana-config"
          items:
            - key: bigquery-logs
              path: bigquery-logs.json
```

**Review by smark88 — CHANGES_REQUESTED** [review]
See general comment.

**Review by smark88 — APPROVED** [review]

**Comment by smark88** [comment]
👍

**Pull request merged**
