### PR TITLE
DR-1964 Make subscription and tenant id fields in the BillingProfileModel UUIDs and not strings

### PR DESCRIPTION
**Pull request by nmalfroy**

### CODE REVIEW

**Comment by samanehsan** [comment]
Looks like one of the integration tests failed

**Comment by nmalfroy** [comment]
Yeah...I think it's actually a unit test.  will put up a fix

**Review by snf2ye — APPROVED** [review]
Assuming tests pass, LGTM!

**Review by samanehsan — APPROVED** [review]
Lgtm once the tests pass!! ☀️

**Pull request merged**
