### PR TITLE
DR-1027 part 1: Kubernetes client utils

### PR DESCRIPTION
**Pull request by marikomedlock**
First draft of utils class for calling Kubernetes from a client.

This class will soon be moved into a separate Gradle sub-project, but that's not quite ready for review, yet. Since Shelby needs this sooner rather than later, I'm putting up this PR with the code in an existing location to hopefully reduce the need for duplicate coding effort.

### CODE REVIEW

**Review by snf2ye — APPROVED** [review]
This is awesome, thank you @marikomedlock ! I pulled this down and it worked for me.

**Review by ddietterich — APPROVED** [review]
lgtm

**Review by fboulnois — APPROVED** [review]
lgtm, great work!

**Comment by marikomedlock** [comment]
All integration test failures are due to rate limit error (1) or permissions errors (the rest).

**Pull request merged**
